// Generated by CoffeeScript 1.9.2
(function() {
  var api, arrayToList, ld, paramsToCacheKey, pb, ref;

  ld = require('lodash');

  pb = require('promise-breaker');

  api = exports.api = {
    fullname: "current-game-v1.0",
    name: "current-game",
    version: "v1.0"
  };

  makeUrl = function(region, obRegion, summId){
    return `https://${region}.api.pvp.net/observer-mode/rest/consumer/getSpectatorGameInfo/${obRegion}/${summId}`;
  }

  exports.methods = {
    getCurrentMatch: pb["break"](function(region, summId) {
      var obRegion = region.toUpperCase();
      obRegion = (obRegion !== 'KR' && obRegion !== 'RU') ? obRegion + '1' : obRegion;
      if(obRegion === 'OCE1') obRegion = 'OC1';
      if(obRegion === 'EUNE1') obRegion = 'EUN1';

      var cacheParams, ref1, ref2, ref3, requestParams;
      requestParams = {
        caller: "getCurrentMatch",
        region: region,
        url: makeUrl(region, obRegion, summId)
      };
      cacheParams = {
        key: api.fullname + "-current-game-" + region + "-" + summId,
        region: region,
        api: api,
        ttl: 30,
        objectType: 'currentGame',
        params: {summonerId: summId}
      };
      return this._riotRequestWithCache(requestParams, cacheParams);
    })
  };

}).call(this);
